"""rename s3_key to stored_filename

Revision ID: 691b319455af
Revises: 1987d2d68699
Create Date: 2026-07-11 10:45:28.339330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691b319455af'
down_revision: Union[str, Sequence[str], None] = '1987d2d68699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files",
        "s3_key",
        new_column_name="stored_filename",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files",
        "stored_filename",
        new_column_name="s3_key",
    )
    # ### end Alembic commands ###
